### ISSUE TITLE
Doesn't build on Mac OS X

### ISSUE THREAD

**Issue by willglynn** [haakonnessjoen/MAC-Telnet#13]
These tools don't build on Mac OS X but they're not far that from doing so. I understand it's titled "MAC-Telnet for Linux", so this might not be of concern, but I had a need to run `mactelnet` and `mndp` on Mac OS X, so I made it work.

This issue is intended to track the general problem that these tools don't build on Darwin.

**Comment by haakonnessjoen** [comment]
Thanks to a pull request by @quentinmit it is now possible to build all tools in OS X too now. I have updated the readme to remove the "Linux" part.
