### ISSUE TITLE
Question about develop

### ISSUE THREAD

**Issue by boospy** [haakonnessjoen/MAC-Telnet#15]
Hello and nice evening :)

I would like to know whether the project is still actively developed?

Thanks and best regards

**Comment by haakonnessjoen** [comment]
Hi,

Yes it is. Why do you ask?

Regards,
Håkon

On 12 August 2015 at 23:23, Mario Loderer <notifications@github.com> wrote:

> Hello and nice evening :)
>
> I would like to know whether the project is still actively developed?
>
> Thanks and best regards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haakonnessjoen/MAC-Telnet/issues/15>.
>



-- 
Håkon

**Comment by boospy** [comment]
I only user, i have seen on starpage that a lot of files where changed many years ago... that's why I've asked.

**Comment by haakonnessjoen** [comment]
It's fully functional. So there is not much to do with it at this time, hence less commits. If you have any ideas for improvement, be sure to add a feature request issue.

mactelnet is already distributed with debian. Although a older version than the current HEAD version.

Your colleague could use this as a starting point:
https://github.com/haakonnessjoen/MACTelnet-Debian-Packaging

**Comment by boospy** [comment]
Oh, i don't know why i havent seen this packages. Thanks for the info and best Regards!
