### ISSUE TITLE
mactelnetd wont bind to an interface without an IP address

### ISSUE THREAD

**Issue by apathyuk** [haakonnessjoen/MAC-Telnet#17]
Hello

I am seeing an issue where mactelnetd will not bind before an ip address is allocated to the interface.

I want to be able to use mactelnet to get back into a box in the case where it is unable to dhcp an address but mactelnetd refuses to start if the network interface does not have an IP address.

Can you see a way around this?

James

**Comment by haakonnessjoen** [comment]
Hi,

Could you try if removing/adding the -n option to mactelnetd helps with your issue?

What kind of distribution are you running?

**Comment by haakonnessjoen** [comment]
No more response from reporter. I'll assume the issue was resolved.

**Comment by hnkeyang** [comment]
I had the same problem, tested removing/adding -n was not help
run mactelnetd in gdb, exit on Unable to find any valid network interfaces 

1102		if (interface_count == 0) {
(gdb) 
1103			syslog(LOG_ERR, _("Unable to find any valid network interfaces\n"));
(gdb) 
1104			exit(1);
(gdb)
