### ISSUE TITLE
freeze on RouterOS->mactelnetd login attempt

### ISSUE THREAD

**Issue by cypa** [haakonnessjoen/MAC-Telnet#23]
from time to time successfull session freezes for a few minutes (ifdown eth1 does not change this behaviour, recall I've eth0+eth1 on the same subnet)

next segfault was caught at login attempt with both eth0 and eth1 up
/var/log/messages:
Sep 28 02:51:48 asterisk mactelnetd[2692]: Bound to 0.0.0.0:20561
Sep 28 02:51:48 asterisk mactelnetd[2692]: Listening on eth1 for 90:2b:34:a9:be:fa
Sep 28 02:51:48 asterisk mactelnetd[2692]: Listening on eth0 for 10:fe:ed:1:43:cf
Sep 28 02:51:48 asterisk mactelnetd[2692]: Listening on eth1.205 for 90:2b:34:a9:be:fa
Sep 28 02:51:48 asterisk mactelnetd[2692]: Listening on eth2.205 for f8:1a:67:2:c9:0
Sep 28 02:51:48 asterisk mactelnetd[2692]: Listening on lxcbr0 for aa:20:8:23:8a:4d
Sep 28 02:53:34 asterisk mactelnetd[2785]: (703) User asurkov logged in.
Sep 28 02:55:48 asterisk mactelnetd[2886]: (716) User asurkov logged in.
Sep 28 02:56:36 asterisk kernel: mactelnetd[2701]: segfault at 0 ip 00274c3f sp bfca57a4 error 4 in libc-2.12.so[1fb000+190000]

**Comment by cypa** [comment]
shall try ...

**Comment by haakonnessjoen** [comment]
Reopen if you manage to get a dump :)
