### ISSUE TITLE
Won't compile macOS Sierra

### ISSUE THREAD

**Issue by mpalladi** [haakonnessjoen/MAC-Telnet#28]
Please add the dependency ( brew install automake ) 

Compile error follows

gcc -DFROM_MACTELNET -g -O2  -L/opt/local/lib  -o mactelnet mactelnet-mactelnet.o mactelnet-protocol.o mactelnet-console.o mactelnet-interfaces.o mactelnet-md5.o mactelnet-mndp.o mactelnet-autologin.o
Undefined symbols for architecture x86_64:
  "_libintl_bindtextdomain", referenced from:
      _main in mactelnet-mactelnet.o
      _mndp in mactelnet-mndp.o
  "_libintl_gettext", referenced from:
      _drop_privileges in mactelnet-mactelnet.o
      _main in mactelnet-mactelnet.o
      _handle_packet in mactelnet-mactelnet.o
      _send_udp in mactelnet-mactelnet.o
      _add_control_packet in mactelnet-protocol.o
      _add_packetdata in mactelnet-protocol.o
      _mndp_add_attribute in mactelnet-protocol.o
      ...
  "_libintl_setlocale", referenced from:
      _main in mactelnet-mactelnet.o
      _mndp in mactelnet-mndp.o
  "_libintl_textdomain", referenced from:
      _main in mactelnet-mactelnet.o
      _mndp in mactelnet-mndp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [mactelnet] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by haakonnessjoen** [comment]
I would guess the compile error is because you didn't do brew install gettext as per instructions?

**Comment by mpalladi** [comment]
I did follow the instructions. It is installed

Aslan-2:~ mpalladi$ gettext -h
Usage: gettext [OPTION] [[TEXTDOMAIN] MSGID]
or:    gettext [OPTION] -s [MSGID]...

Display native language translation of a textual message.

  -d, --domain=TEXTDOMAIN   retrieve translated messages from TEXTDOMAIN
  -e                        enable expansion of some escape sequences
  -E                        (ignored for compatibility)
  -h, --help                display this help and exit
  -n                        suppress trailing newline
  -V, --version             display version information and exit
  [TEXTDOMAIN] MSGID        retrieve translated message corresponding
                            to MSGID from TEXTDOMAIN

If the TEXTDOMAIN parameter is not given, the domain is determined from the
environment variable TEXTDOMAIN.  If the message catalog is not found in the
regular directory, another location can be specified with the environment
variable TEXTDOMAINDIR.
When used with the -s option the program behaves like the 'echo' command.
But it does not simply copy its arguments to stdout.  Instead those messages
found in the selected catalog are translated.
Standard search directory: /usr/local/Cellar/gettext/0.19.8.1/share/locale

**Comment by haakonnessjoen** [comment]
What does configure say around this part?
```
checking for GNU gettext in libc... no
checking for iconv... yes
checking for working iconv... yes
checking how to link with libiconv... -liconv
checking for GNU gettext in libintl... no
```
You could try without gettext as it seems to be able to use libintl if it is present.

**Comment by mpalladi** [comment]
checking for GNU gettext in libc... no
checking for iconv... yes
checking for working iconv... yes
checking how to link with libiconv... -liconv
checking for GNU gettext in libintl... yes
checking whether to use NLS... yes
checking where the gettext function comes from... external libintl
checking how to link with libintl... -L/usr/local/lib -lintl -Wl,-framework -Wl,CoreFoundation

**Comment by haakonnessjoen** [comment]
Have you tried running make agein? It seems to figure out to add -liconv But the gcc line you pasted seems to be missing -liconv

**Comment by haakonnessjoen** [comment]
Please reopen if you have more evidence that the problem is in the sources and not user fault :)
