### ISSUE TITLE
macping: "open_bpf: Resource busy"

### ISSUE THREAD

**Issue by traffsh0w** [haakonnessjoen/MAC-Telnet#29]
I'm not sure it is an issue, but I can't macping any mac address because of this error:
`open_bpf: Resource busy`

My setup is:
- MacBook Pro (Retina, 15-inch, Mid 2015)
- macOS Sierra 10.12.3 (16D32)
- MAC-Ping 0.4.4

Reproduce:
`bash-3.2# macping 6C:3B:6B:59:9F:6A` 
`open_bpf: Resource busy`

Virtual Machine:
I've checked this behavior on virtual macOS Sierra 10.12.3 and it is working fine.
The only difference is that VM has only one network interface.

Please advise.
Thanks!

**Comment by SerhiyMakarenko** [comment]
I can confirm this issue. Also on my Mac's installed macOS Sierra 10.12.3 (16D32).

My configuration:

- Mac Pro Late 2008;
- Mac mini Late 2012;
- MAC-Ping 0.4.3.

Please, advice.

Thanks, Serhiy

**Comment by SerhiyMakarenko** [comment]
Also, I have found one more thing. I have checked how works mactelnet on Mac mini with one physical ethernet interface and were surprised. On Mac machine with one physical ethernet all working fine. But the output of the command a little bit weird:

`bpf_write: Network is down
6c:3b:45:56:49:30 56 byte, ping time 0.41 ms
bpf_write: Network is down
6c:3b:45:56:49:30 56 byte, ping time 0.35 ms
bpf_write: Network is down
6c:3b:45:56:49:30 56 byte, ping time 0.36 ms
bpf_write: Network is down
6c:3b:45:56:49:30 56 byte, ping time 0.36 ms
bpf_write: Network is down
6c:3b:45:56:49:30 56 byte, ping time 0.34 ms

5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 0.34/0.36/0.41 ms`

Maybe this info would be helpfull.

**Comment by antwal** [comment]
Hi, 

confirm same problem on OSX 10.9.x and 10.10.x

on mac with multiple interfaces there are:
`ls -al /dev/bpf*
crw----r--  1 root  wheel   23,   0 21 Giu 15:48 /dev/bpf0
crw----r--  1 root  wheel   23,   1 21 Giu 15:48 /dev/bpf1
crw----r--  1 root  wheel   23,   2 21 Giu 15:48 /dev/bpf2
crw----r--  1 root  wheel   23,   3 21 Giu 15:48 /dev/bpf3
crw----r--  1 root  wheel   23,   4 21 Giu 17:13 /dev/bpf4`

bpf0 is lo0
bpf1 is en0
bpf2 is en1
etc...

if change the active interface (en1 now) on interfaces.c on line 281, on OSX 10.9.x i have this output:

`sudo ./src/macping 00:0c:42:b7:bb:7d
0:c:42:b7:bb:7d 56 byte, ping time 1,23 ms
0:c:42:b7:bb:7d 56 byte, ping time 1,72 ms
0:c:42:b7:bb:7d 56 byte, ping time 1,31 ms
0:c:42:b7:bb:7d 56 byte, ping time 1,93 ms
0:c:42:b7:bb:7d 56 byte, ping time 4,08 ms`

I can correct the problem, just finish all the tests

**Comment by haakonnessjoen** [comment]
This should be fixed in latest release
