### ISSUE TITLE
install problem: autogen.sh error

### ISSUE THREAD

**Issue by shorrey** [haakonnessjoen/MAC-Telnet#30]
OS: Ubuntu 14.04 LTS

`$ ./autogen.sh 
aclocal: warning: couldn't open directory 'm4': Нет такого файла или каталога
Can't exec "autopoint": Нет такого файла или каталога at /usr/share/autoconf/Autom4te/FileUtils.pm line 345.
autoreconf: failed to run autopoint: Нет такого файла или каталога
autoreconf: autopoint is needed because this package uses Gettext
`

just need to:
`mkdir m4`

and
`$ sudo apt-get install autopoint`

**Comment by haakonnessjoen** [comment]
Hi,

I will investigate.

But just a tip: on Ubuntu you could just do ```sudo apt-get install mactelnet-client``` or ```sudo apt-get install mactelnet-server```

**Comment by shorrey** [comment]
thanks! i didn't know that
