### ISSUE TITLE
Use interface other than eth0

### ISSUE THREAD

**Issue by bbs2web** [haakonnessjoen/MAC-Telnet#31]
We sometimes interface with routers on interfaces other than eth0, it would be extremely useful to be able to set the required interface, eg:
`./mactelnet -i vlan14 4c:5e:0c:02:71:90`

**Comment by haakonnessjoen** [comment]
By default it tries to connect on all interfaces with ethernet capabilities. You could try to use with or without -n but that will need user privilege elevation. If you use -n it uses raw sockets which may have better success at sending to each individual interface.
