### ISSUE TITLE
Compile issue on RHEL5

### ISSUE THREAD

**Issue by fumok** [haakonnessjoen/MAC-Telnet#32]
Hi,

I'm trying to compile under RHEL5, but the automake version is very old (1.9 vs 2.68). Can you help me?

Thanks.

**Comment by antwal** [comment]
Hi,

i have tested it on RHEL5/6:

`yum update `
`yum install autoconf automake gettext gettext-devel libtool m4`

## NOTE:
gettext-devel is required for autopoint

## Attached logs files for autogen, configure, make

[MAC-Telnet_autogen.txt](https://github.com/haakonnessjoen/MAC-Telnet/files/1135582/MAC-Telnet_autogen.txt)

[MAC-Telnet_configure.txt](https://github.com/haakonnessjoen/MAC-Telnet/files/1135567/MAC-Telnet_configure.txt)

[MAC-Telnet_make.txt](https://github.com/haakonnessjoen/MAC-Telnet/files/1135583/MAC-Telnet_make.txt)


Working without errors... 

Thanks.

**Comment by fumok** [comment]
I Understand why it doesn't compile on RHEL5: glibc!

Functions le32toh and htole16 are introduced in glibc 2.9. RHEL5 is build on top on 2.5. No Way.

Thanks.

**Comment by antwal** [comment]
Hi, i have tried on RHEL, why i use this OS and not have problem to build application; maybe if you use unofficial repositories, you may have problems. I can see tonight which versions i've installed glibc

**Comment by fumok** [comment]
I try to build on a fresh install (RHEL5). Anyway it is virtually impossible to upgrade glibc on a RHEL system.
But if you have done some magic, I'm glad to obtain a binary for RHEL5 😃 .

**Comment by antwal** [comment]
hi,

I honestly do not remember if on the 5th I installed the packages from the official channels or manually; On 6 and 7 there are no problems ...

If I remember, there was an article on the official forum: [RedHat Community Forum](https://access.redhat.com/discussions?product=25) or Alternatively, version 5 is too obsolete, I recommend this article [RHEL5 Upgrade](https://access.redhat.com/articles/1211223)

I hope to be able to integrate other OSs on Travis CI so we can properly verify the application build

**Comment by fumok** [comment]
I know well RHEL5 is obsolete, but I must maintain those legacy systems. I know also I can't expect mac-telnet builds on those old systems (2007).

Thaks alot for all support.

**Comment by antwal** [comment]
Hi, 

you use this version [5.11](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/5/html/5.11_Release_Notes/index.html) ?

**Comment by fumok** [comment]
No I use 5.9, it changes little or nothing.
