### ISSUE TITLE
Unable to run script via browser

### ISSUE THREAD

**Issue by kevinp1005** [haakonnessjoen/MAC-Telnet#34]
I'm trying to execute an expect script through php in browser, but it's throwing an expect error saying "**spawn id exp5 not open**". But if I execute the php file directly from terminal it's working fine and I'm able to get the ouput. Same thing with ssh with IP Address, it's working fine through browser and terminal. 

This is my exp file that needs to be called via PHP from browser:

```
#!/usr/bin/expect -f
set timeout -1
spawn mactelnet xx:xx:xx:xx:xx:xx -u admin -p admin
match_max 100000
sleep 1
expect " > "
send "/ip dhcp-server lease print\r"
expect " > "
send "/quit\r"
expect eof
set i 1
while {$i < 51} {
set output [open "/var/www/html/IntegrasiHelpdesk/aktivasi/txt/aaa.txt" "w"]
set outcome $expect_out(buffer)
puts $output $outcome
incr i
}
close $output

```

The php file is just a normal shell exec function :
`shell_exec(<path to my exp file> . '&& ./cekDHCPmac.exp 2>&1 &');`

**Comment by antwal** [comment]
Hi,

sometimes i also use expect; the error "spawn id exp5 not open" is the password/command prompt fails

my simple example:

`set timeout 120`
`spawn "mactelnet" "XX:XX:XX:XX:XX:XX"`
`expect -nocase "login:"`
`send "admin\r"`
`expect -nocase "password:"`
`send "password\r"`
`expect "% "`
`send -- "r\r"`
`expect "% "`
`expect " > "`

or you can try handling the timeout on expect, example:

`expect {`
`  "Password:" {`
`    send "password\r"`
`  }`
`  timeout {`
`    exit 1`
`  }`
`}`

Thanks.

**Comment by haakonnessjoen** [comment]
Seems like antwal had a fix for you, reopen if his tip didn't help :)
