### ISSUE TITLE
Outputs garbage and dies after login most of the time with Mikrotik >=5.20

### ISSUE THREAD

**Issue by ghost** [haakonnessjoen/MAC-Telnet#4]
Hello, we now usually get:

Connecting to 2:2:0:99:95:9...done

  MMM      MMM       KKK                          TTTTTTTTTTT      KKK
  MMMM    MMMM       KKK                          TTTTTTTTTTT      KKK
  MMM MMMM MMM  III  KKK  KKK  RRRRRR     OOOOOO      TTT     III  KKK  KKK
  MMM  MM  MMM  III  KKKKK     RRR  RRR  OOO  OOO     TTT     III  KKKKK
  MMM      MMM  III  KKK KKK   RRRRRR    OOO  OOO     TTT     III  KKK KKK
  MMM      MMM  III  KKK  KKK  RRR  RRR   OOOOOO      TTT     III  KKK  KKK

  MikroTik RouterOS 5.20 (c) 1999-2012       http://www.mikrotik.com/

V4^R
V4�^B^@^@^@^@E^Z��a^K�lOcP���V4^R
��a^K�lOcP���V4�^C^@^@^@^EadminV4^R
^@^@^@^EadminV4�^@^@^@^ExtermV4^R
^@^@^@^ExtermV4�^E^@^@^@^BO^@V4^R
^@^@^@^ExtermV4�^E^@^@^@^BO^@V4�^F^@^@^@^B^@Connection closed.

.

I tried debugging it and found out, that the text it prints + the garbage is all outputed on a single line in mactelnet.c (line 297, as of writing)

			/* If the (remaining) data did not have a control-packet magic byte sequence,
			   the data is raw terminal data to be outputted to the terminal. */
			else if (cpkt.cptype == MT_CPTYPE_PLAINDATA) {
				cpkt.data[cpkt.length] = 0;
>				fputs((const char *)cpkt.data, stdout);
			}

Then the client sends an ACK and then Mikrotik immediately sends back an end session frame.

Tried compiling with -m32 and -m64 on amd64 system.

**Comment by LatinSuD** [comment]
In my case: It works when compiled on a modern 64 bit Debian, and it fails when compiled on an old 32 bit Fedora.

**Comment by haakonnessjoen** [comment]
LatinSuD, so you had problems earlier, but it was fixed by compiling the latest version?

**Comment by LatinSuD** [comment]
Yes, the latest version of mactelnet works with any version of RouterOS.
