### ISSUE TITLE
Fix - No TTY mode

### ISSUE THREAD

**Issue by StellaTeam** [haakonnessjoen/MAC-Telnet#44]
In order to be able to use mactelnet from PHP (and so without terminal), terminal size should be specified.

So, you have to use login flags 

https://wiki.mikrotik.com/wiki/Manual:Console_login_process#Console_login_options

Or the program has do declare it

Here is a patch i propose.

```
diff --git a/src/mactelnet.c b/src/mactelnet.c
index 8358673..ce2db40 100644
--- a/src/mactelnet.c
+++ b/src/mactelnet.c
@@ -247,6 +247,11 @@ static void send_auth(char *username, char *password) {
                height = htole16(height);
                plen += add_control_packet(&data, MT_CPTYPE_TERM_WIDTH, &width, 2);
                plen += add_control_packet(&data, MT_CPTYPE_TERM_HEIGHT, &height, 2);
+       } else {
+               width = htole16(0);
+               height = htole16(0);
+               plen += add_control_packet(&data, MT_CPTYPE_TERM_WIDTH, &width, 2);
+               plen += add_control_packet(&data, MT_CPTYPE_TERM_HEIGHT, &height, 2);
        }
 
        outcounter += plen;
```

If you don't, you get disconnected and so the program is no more usable from PHP (or any non TTY environment).

**Comment by haakonnessjoen** [comment]
Have you tested it? Also I guess you could leave out the htole16() part. Since 0 is what it is.

Want to send a pull request, if it does work?

**Comment by StellaTeam** [comment]
Hi @haakonnessjoen 

Yes, the code has been tested and is working.
Indeed, htole16() don't seem to be necessary.

Yes, sure, this patch is for community ;-)

**Comment by haakonnessjoen** [comment]
But could you send it as a pull request? :)

**Comment by StellaTeam** [comment]
Done ! ;)

https://github.com/haakonnessjoen/MAC-Telnet/pull/45

**Comment by haakonnessjoen** [comment]
Was merged two years ago
