### ISSUE TITLE
How to auto login?

### ISSUE THREAD

**Issue by sgeto** [haakonnessjoen/MAC-Telnet#52]
- **MAC Telnet version:** 
From git

- **Operating system and architecture:** 
Unix-like

- **Issue** 
Hey,
I have a hopefully very simple question regarding auto login:

autologin.c seems to in charge of parsing that file, but I still can't get the syntax right.
Can somebody please shed some light on this and/or post an example file?

Thank you

- **Log**

**Comment by haakonnessjoen** [comment]
Sorry for the 4 year late reply. A typical ~/.mactelnet autologin file would be:

```
[myrouter]
user=admin
password=12345

[c4:ad:34:a6:e:cb]
user=admin
password=one23
```

If you do `mactelnet myrouter` it would auto login using the first configuration in the file. If you would do `mactelnet c4:ad:34:a6:e:cb` it would use the second one.
