### ISSUE TITLE
No longer builds on MAC

### ISSUE THREAD

**Issue by jmcguckin** [haakonnessjoen/MAC-Telnet#54]
Your build instructions are incomplete. First, one gets error about aclocal can't be found, then
one gets the error "C compiler cannot create executables'

If this project is abandoned, it should be deleted or marked as 'abandoned - subject to bitrot'

**Comment by haakonnessjoen** [comment]
It is not abandoned, but there is a blocking problem with mikrotik having updated their authentication system, but ironically they do not want to help the open source community the least. So further development is a bit futile.

**Comment by haakonnessjoen** [comment]
Also, the error message you reported, is what you would get, if you do not follow the installation instructions, are you sure you followed them?
