### ISSUE TITLE
Ability to transfer files

### ISSUE THREAD

**Issue by jkroonza** [haakonnessjoen/MAC-Telnet#55]
- I've just installed MAC-Telnet 0.4.4
- Currently the (newly obtained) device is using RouterOS 6.43.9.
- The idea is to generate an RSC script programmatically which is then to be deployed to a MT Router (Running RouterOS).
- Since after a /system reset-configuration there is no IPs it would be ideal if we can get a way to copy the script over using MAC-Telnet.  Alternatively we'll just have to rely on the default IPs and use run-after-reset and pre-copy the script using scp (the downside of which is host keys that's going to keep getting in the way).

Not critical I guess, but would be a nice feature.

**Comment by haakonnessjoen** [comment]
I think this is a bit out of the scope of this project. You could probably add the script by adding it via the shell though? Maybe create a bash script that pipes the required commands to add the script into mactelnet?
