### ISSUE TITLE
Error binding to 0.0.0.0:5678

### ISSUE THREAD

**Issue by lexavey** [haakonnessjoen/MAC-Telnet#56]
- **MAC Telnet version:** MAC-Telnet 0.4.4
- **Operating system and architecture:** Linux 0x 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux ( Windows SubSystem )
- **Issue** 
I am try to using command -l List/Search for routers nearby (MNDP).
i got error like that, how i can fix this
- **Log**
melex@0x:/tmp/haakonnessjoen-MAC-Telnet-db80dc7$ mactelnet -l
Error binding to 0.0.0.0:5678

**Comment by haakonnessjoen** [comment]
Something else is listening on the 5678 port. I haven't used WSL, so I don't know how that works. But if it shares the network interface with windows, maybe you had winbox running at the same time?
