### ISSUE TITLE
Auth incompatible with firmware 6.45.7 :-(

### ISSUE THREAD

**Issue by gorec2005** [haakonnessjoen/MAC-Telnet#59]
- **MAC Telnet version: MAC-Telnet 0.4.4** 
- **Operating system and architecture: Linux 3 5.0.0-34-generic #36-Ubuntu SMP Wed Oct 30 05:16:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
** 
- **Issue: with latest firmware (MikroTik 6.45.7 (stable) RB2011UiAS-2HnD) can't login with "Login failed, incorrect username or password" error** 
- **# mactelnet 4C:5E:0C:5A:9B:5C
Login: admin
Password: 
Connecting to 4c:5e:c:5a:9b:5c...done
Login failed, incorrect username or password
Connection closed.**
login and pass not empty and correct!

**Comment by haakonnessjoen** [comment]
Same as issue #42
