### ISSUE TITLE
heap corruption

### ISSUE THREAD

**Issue by BrainSlayer** [haakonnessjoen/MAC-Telnet#60]
https://github.com/haakonnessjoen/MAC-Telnet/blob/db80dc7fcc7ebf7f85f511e381445ba521c4eae6/src/mactelnetd.c#L955

the referenced line (and 3 others related to list_remove_connection will lead to heap corruption. you cannot use a local stack object as part of this list. this object will turn invalid after leaving the loop and the content of this object will be overwriten by other stack allocated objects. i found this issue while debugging a crash on mips64 systems. the temp object in list must be allocated using malloc instead
consider that the referenced line is not the only line suffering from the same error

**Comment by haakonnessjoen** [comment]
Thanks! Yes, that was dirty! I will fix :)

**Comment by BrainSlayer** [comment]
that wasnt just dirty. according what i have seen this can lead to code execution :-)
i already fixed in in my tree using tmp as *tmp pointer using calloc. is this correct?

**Comment by haakonnessjoen** [comment]
The local stack variable is not really added to the list, it is only used to trick the foreach to continue on, but it is declared a bit late yes, so it is problematic. As I look over the code now, the foreach should probably have been a foreach_safe instead since the list is being modified, and then it would not need the tmp.next part at all.

**Comment by BrainSlayer** [comment]
i just can say that it crashed because the pointer changed within the loop, so ->next turned into something else than NULL, so a exception happend. more interesting on mips64 i got a bad opcode fault. and the main problem here is that the local stack variable is declared inside the loop and not outside which would work if your description is correct. so the stack pointer wont get changed and nothing gets modified.

**Comment by haakonnessjoen** [comment]
I will push a fix in a few minutes
