### ISSUE TITLE
FreeBSD instructions minor typo

### ISSUE THREAD

**Issue by smileymattj** [haakonnessjoen/MAC-Telnet#61]
- **MAC Telnet version:** 
README.markdown

- **Operating system and architecture:** 
FreeBSD

- **Issue** 
Currently reads:
> FreeBSD
> Dependencies: clang (gcc or similar), automake, autoconf
> 
> To install dependencies on **Debian/Ubuntu** based systems:

Also is wget, gcc and gmake implied here?  
> pkg install automake autoconf gettext-tools

On base install I had to add:
 > pkg install automake autoconf gettext-tools gcc gmake wget

Thanks for the Great work, best of luck resolving the new login encryption.

**Comment by xorrkaz** [comment]
FYI, I have created a port/package for this for FreeBSD.  you can `pkg install mac-telnet`.

**Comment by haakonnessjoen** [comment]
This was updated in the readme at some point. Nice with a FreeBSD package. I will soon release a new version, I will ping you when it is ready.

**Comment by haakonnessjoen** [comment]
Forgot to ping, but better late than never?
