### ISSUE TITLE
Login options not working with updated auth scheme.

### ISSUE THREAD

**Issue by inean** [haakonnessjoen/MAC-Telnet#77]
Hi, tried HEAD version of mactelnet. Works great with ROS 7.5 but, to be able to use an expect script, disable colors is a must. Unfortunately, use color options as specified in https://help.mikrotik.com/docs/display/ROS/Command+Line+Interface makes authentication fail.

example:
login: admin -> works
login: admin+c80w -> fails

**Comment by haakonnessjoen** [comment]
@khefifioussama Pretty sure you didn't mean to write that here?

**Comment by khefifioussama** [comment]
Ok I interstand
