### ISSUE TITLE
autogen.sh not working as it should on Ubuntu 22.04

### ISSUE THREAD

**Issue by guuslangelaar0** [haakonnessjoen/MAC-Telnet#80]
- **MAC Telnet version:** 
> Latest version
- **Operating system and architecture:** 
> Ubuntu 22.04 - Linux 5.15.0-52-generic x86_64 (VM)
- **Issue** 
> Performing `autogen.sh` returns following error
- **Log**
```
./configure: line 8210: syntax error near unexpected token `CRYPTO,'
./configure: line 8210: `PKG_CHECK_MODULES(CRYPTO, libcrypto >= 1.0.2)'
```

**Comment by Kearlock** [comment]
Got the same issue.
"apt-get install pkg-config" works fine for me.

**Comment by Applepi** [comment]
New version uses autoconf later than what is in apt repo...

**Comment by haakonnessjoen** [comment]
This should now work as expected.
