### ISSUE TITLE
Does not work with RouterOS 7.6

### ISSUE THREAD

**Issue by asy972** [haakonnessjoen/MAC-Telnet#81]
- **MAC Telnet version:** 

current master snapshot 

- **Operating system and architecture:** 

Linux

- **Issue** 

$ ./mactelnet -u admin 6c:3b:6b:3f:e7:fa
Password:
Connecting to 6c:3b:6b:3f:e7:fa...done
Login failed, incorrect username or password
Connection closed.

- **Log from device**

jan/02/1970 00:06:16 system,error,critical login failure for user admin from 00:1C:C0:18:FC:89 via mac-telnet

This is my first experience using mac-telnet. The device is available by IP via classic telnet or by MAC address via Winbox.

**Comment by haakonnessjoen** [comment]
Could you try to replicate this issue with the current master branch version?
