### ISSUE TITLE
Hangs indefinitely on unknown user

### ISSUE THREAD

**Issue by merlinthemagic** [haakonnessjoen/MAC-Telnet#82]
- **MAC Telnet version:** master December 22, 2022
- **Operating system and architecture:** ubuntu 22.10 / arm64 
- **Issue** Hangs indefinitely on unknown username
- **Target**: RouterOS 7.6 / arm
- **Log**

Bash (Logging in with account that does NOT exist):
mactelnet -A dc:2c:6e:02:01:00
Login: **userThatDoesNotExist**
Password: anySecret

Output: Invalid salt length: 33 (instead of 16 or 49) received from server dc:2c:6e:02:01:00
Result: Process hangs and never exits

Bash:
mactelnet -A dc:2c:6e:02:01:00
Login: **userThatDoesExist**
Password: wrongSecret

Output: Login failed, incorrect username or password
Result: bash received a SIGCHLD and exits

- **Notes**

Clearly RouterOS has a problem here and is leaking information regarding user accounts, but MacTelnet should still exit.

**Comment by merlinthemagic** [comment]
Opened SUP-101713 with Mikrotik to resolve.

**Comment by haakonnessjoen** [comment]
Why do you mean it is leaking information?

**Comment by merlinthemagic** [comment]
@haakonnessjoen the system is informing an unauthenticated user if an account exists on the system or not. 

Login with right account + wrong password should be indistinguishable from wrong account + password.

Mikrotik Sergejs ack the issue and wil fix in upcoming release, but given the multitude of devices that will run RouterOS <7.6 for years to come, this client implementation should still handle the exception.

**Comment by haakonnessjoen** [comment]
Ah yes, I did not see that you wrote "UserThatDoesExist" vs "UserThatDoesNotExist". So I was confused by the issue reported. Sorry about that, and I agree with you. Please update when you get a response from them. PS. I am glad you have good use of the wireshark mactelnet plugin I also wrote 12 years ago. :D Wow time flies...

**Comment by merlinthemagic** [comment]
@haakonnessjoen I edited the initial report to emphasize how to reproduce the issue, you are right it was easy to miss the username differed. 

The wireshark plugin makes life so much easier :)

Ill update when MT reports back. In the mean time, i submitted a pull request based on my shaky C skills.

Mange Tak :)

**Comment by csch42** [comment]
> The wireshark plugin makes life so much easier :)
> 
> 

😳😳😳 What did I miss???

	Clemens

**Comment by haakonnessjoen** [comment]
This is now fixed in master
