### ISSUE TITLE
A Return_Local Error was found

### ISSUE THREAD

**Issue by fatshi** [haakonnessjoen/MAC-Telnet#87]
- **MAC Telnet version: Latest** 
- **Operating system and architecture: All** 
- **Issue: A Return_Local Error was found** 

in protocol.c, struct mt_mndp_info *parse_mndp(const unsigned char *data, const int packet_len), has a Return_Local bug:
<img width="675" alt="image" src="https://github.com/haakonnessjoen/MAC-Telnet/assets/10611970/828f7ce3-d163-454d-afe5-5b19fa113ae6">
<img width="221" alt="image" src="https://github.com/haakonnessjoen/MAC-Telnet/assets/10611970/8b9762e8-2edd-4025-be28-efddea0144c3">

returned a pointer to a local variable

**Comment by haakonnessjoen** [comment]
It's a static variable, so it remains after the function is done. And mactelnet/mndp is single threaded, so is this really an issue? It is used only two places which respect that fact. The data is always just presented right away by the two places that uses it.

**Comment by fatshi** [comment]
Oh，You are right, My scanner just miss the static keyword
