### ISSUE TITLE
can't find openssl (1.1.0 crypto lib)

### ISSUE THREAD

**Issue by JustAbsolute** [haakonnessjoen/MAC-Telnet#88]
- **MAC Telnet version:** 
- **Operating system and architecture:** 
- **Issue** 
- **Log**

Hi!
I need help, I did it according to the instructions of Mac OS X, but this problem...
MacBook Pro 14.1 (M1Pro) Sonoma 14.4.1

./autogen.sh
...
configure: error: in '/Users/justabsolute/haakonnessjoen-MAC-Telnet-194aa57':
configure: error: can't find openssl >= 1.1.0 crypto lib

make all install
make: *** No rule to make target `all'.  Stop.

echo $OPENSSL_PATH
/opt/homebrew/opt/openssl@1.1

ls -l /Users/justabsolute/haakonnessjoen-MAC-Telnet-194aa57
total 1464
-rw-r--r--   1 justabsolute  staff   93787 24 апр 16:46 ABOUT-NLS
-rw-r--r--   1 justabsolute  staff     515 22 апр 22:18 Dockerfile
-rw-r--r--   1 justabsolute  staff   18092 22 апр 22:18 LICENSE
-rw-r--r--   1 justabsolute  staff     183 22 апр 22:18 Makefile.am
-rw-r--r--   1 justabsolute  staff   25396 24 апр 16:46 Makefile.in
-rw-r--r--   1 justabsolute  staff    7162 22 апр 22:18 README.markdown
-rw-r--r--   1 justabsolute  staff   42562 24 апр 16:46 aclocal.m4
-rwxr-xr-x   1 justabsolute  staff     372 22 апр 22:18 autogen.sh
drwxr-xr-x  11 justabsolute  staff     352 24 апр 16:46 autom4te.cache
-rwxr-xr-x   1 justabsolute  staff    7400 24 апр 16:46 compile
drwxr-xr-x   7 justabsolute  staff     224 24 апр 16:48 config
-rwxr-xr-x   1 justabsolute  staff   49348 24 апр 16:46 config.guess
-rw-r--r--   1 justabsolute  staff   40443 24 апр 16:46 config.log
-rwxr-xr-x   1 justabsolute  staff   18717 24 апр 16:46 config.rpath
-rwxr-xr-x   1 justabsolute  staff   35276 24 апр 16:46 config.sub
-rwxr-xr-x   1 justabsolute  staff  323616 24 апр 16:46 configure
-rw-r--r--   1 justabsolute  staff    3330 22 апр 22:18 configure.ac
-rwxr-xr-x   1 justabsolute  staff   23568 24 апр 16:46 depcomp
drwxr-xr-x   8 justabsolute  staff     256 24 апр 16:46 doc
-rwxr-xr-x   1 justabsolute  staff   15358 24 апр 16:46 install-sh
drwxr-xr-x  35 justabsolute  staff    1120 24 апр 16:46 m4
-rwxr-xr-x   1 justabsolute  staff    6878 24 апр 16:46 missing
drwxr-xr-x  18 justabsolute  staff     576 24 апр 16:46 po
drwxr-xr-x  26 justabsolute  staff     832 24 апр 16:46 src

**Comment by haakonnessjoen** [comment]
Also, if you followed the instructions in the readme, it is weird that you have openssl@1.1 and not openssl@3 which is what brew would install right now.

```
% brew info openssl
==> openssl@3: stable 3.2.1 (bottled)
```

**Comment by JustAbsolute** [comment]
Thanks a lot! 
I've changed it to version 3 and installed pkg-config, it works)))

**Comment by ctracy** [comment]
Hi there-
Building mactelnet for the first time on macOS. Tried following the instructions on the main page, but it didn't include the brew install pkg-config. I ran into the same issues as the original poster of this issue:

```
checking whether to use NLS... yes
checking where the gettext function comes from... external libintl
checking how to link with libintl... -lintl -Wl,-framework -Wl,CoreFoundation
checking for CoreFoundation/CoreFoundation.h... yes
checking for SystemConfiguration/SystemConfiguration.h... yes
checking for nanosleep in -lrt... no
checking for library containing EVP_MD_CTX_new... no
configure: error: in '/Users/ctracy/work/esnet/mactelnet/haakonnessjoen-MAC-Telnet-ca1df4d':
configure: error: can't find openssl >= 1.1.0 crypto lib
See 'config.log' for more details
```

after running brew install pkg-config, it worked:

```
checking for nanosleep in -lrt... no
checking for pkg-config... /opt/homebrew/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libcrypto >= 1.1.0... yes
checking for arpa/inet.h... yes
```

Perhaps it would be good to update the instructions on the main page to include the brew install pkg-config?

**Comment by haakonnessjoen** [comment]
Thanks. Updated README in 5f541a
