### ISSUE TITLE
can not login to route os V7.14

### ISSUE THREAD

**Issue by ggsnpdsn** [haakonnessjoen/MAC-Telnet#90]
Login: admin
Password: 
Connecting to D4:01:C3:17:5E:D1...done
Login failed, incorrect username or password
Connection closed.
root@Test:~# 

The same username and password can be used to log in through web and Winbox，In addition, I provided the - u and - p parameters on the command line, but still prompted me to enter a username and password

**Comment by ggsnpdsn** [comment]
mactelnet version is 0.4.0

**Comment by haakonnessjoen** [comment]
RouterOS switched encryption. You need to upgrade to mactelnet > 0.5.0
