### ISSUE TITLE
Is the u-p parameter unavailable？

### ISSUE THREAD

**Issue by ggsnpdsn** [haakonnessjoen/MAC-Telnet#91]
root@Test:~# mactelnet  -v
MAC-Telnet 0.5.1
root@Test:~# mactelnet D4:01:C3:17:4E:D2 -u admin -p admin
Login: 

The password and username have been provided on the command line, but there is still a prompt for input，router os is v7.14

**Comment by haakonnessjoen** [comment]
On some getopts you need to have options before arguments, so put the mac address or identityt name at the end
