### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by bmatic385** [haakonnessjoen/MAC-Telnet#97]
- **MAC Telnet version:** 0.6.1
- **Operating system and architecture:** Debian 12.5, kernel 6.1.0-22amd64
- **Issue** Latest version on Docker.io is 0.5.0, Can You please upgrade Docker image ?

Also, when running telnetd v0.5.0 thrught Docker got an error "/build/etc/mactelnetd.users: No such file or directory", and in 0.5.0 telnetd there is no option to add user "-a".

Can't install latest 0.6.1 deb file on latest Debian, dependency hell, libc6 (>= 2.38), libssl3t64 (>= 3.0.0), will brake libssl3 .....

**Comment by haakonnessjoen** [comment]
0.5.0 did not support "-a" option. On latest Debian you should be able to compile it yourself by following the Debian/linux instructions in README.md.
